Harmonize date format
VultureProject/darwin pull request #203
Opened 2020-09-17 12:15 UTC by GregoireGonzalez

# :sparkles: Pull Request Template
:bangbang: Once all the **checklist** is **done** you have to:
  * **stash merge** this pull request
  * **delete** the corresponding **branch**
  * **close** the associated **issue**

## :page_with_curl: Type of change

**Bug fix**: non-breaking change which fixes an issue.

## :bulb: Related Issue(s)

- Resolve #200

## :black_nib: Description

We used to have several different date formats, which are now harmonized in UTC / RFC 3339.

## :dart: Test Environments

### HBSD  12.1
- Redis 5.0.9
- Boost 1.72
- clang++ 10.0.0
- CMake 3.17.3
- Python 3.7

### Ubuntu 20.04
- Redis 5.0.9
- Boost 1.72
- GCC 9.3.0
- CMake 3.16.3
- Python 3.8

## :heavy_check_mark: Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] (**If other changes**) I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

</br>

- [x] :raising_hand: **I certify on my honor that all the information provided is true, and I've done all I can to deliver a high quality code**

2020-09-17 12:46 UTC, HugoSoszynski submitted a review, later dismissed

2020-09-17 14:13 UTC, frikilax requested changes

2020-09-17 14:13 UTC, frikilax commented on manager/manager.py
> +    '{"date":"' + date + '","level":"%(levelname)s","message":"%(message)s"}')
date will always be the same, can't do it this way

2020-09-22 14:03 UTC, frikilax approved these changes

2020-09-22 15:09 UTC, merged