VAST:: ADD SKELETON FOR CMAKE AND TESTS, ADAPT FBUFFER
VultureProject/darwin pull request #214
Opened 2020-12-15 10:18 UTC by frikilax

# CMakeLists
- add VAST file inclusion

# functional tests
- add mock test file

# Test framework
- add an ApproxDict class to check float equality with delta in dictionaries
- add a generic filter function to validate fields in generated filters' alerts

2021-01-25 21:00 UTC, HugoSoszynski requested changes
What is the `tests/tools/utils.py` doing in the PR ?
I can't find where the ApproxDict is used.

2021-01-27 09:22 UTC, frikilax commented on samples/fbuffer/Connectors/AConnector.cpp
> +    }
good catch

2021-01-27 09:29 UTC, frikilax commented on samples/fbuffer/Connectors/SumConnector.cpp
> +                    AConnector(context, darwin::SOFA, filter_socket_path, interval, redis_lists, minLogLen) {}
my bad

2021-01-27 09:58 UTC, HugoSoszynski submitted a review, later dismissed

2021-01-29 14:41 UTC, HugoSoszynski approved these changes

2021-02-01 08:17 UTC, merged